// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCW5AtQmCeOHHQFtR0_R-kS4BPAwOwkMU',
    appId: '1:706777644047:web:674bf10214c3d221adb77a',
    messagingSenderId: '706777644047',
    projectId: 'baladi-bd390',
    authDomain: 'baladi-bd390.firebaseapp.com',
    storageBucket: 'baladi-bd390.firebasestorage.app',
    measurementId: 'G-HV8PEQBPLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZKHwT58ypGmKOXW4xPnSWx5DGTgZd1c',
    appId: '1:706777644047:android:f2007f21b94fafc8adb77a',
    messagingSenderId: '706777644047',
    projectId: 'baladi-bd390',
    storageBucket: 'baladi-bd390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc8mLQlLt4CvA3Ncpb-BVczDgUxHB6UOg',
    appId: '1:706777644047:ios:98bcdf523df8d140adb77a',
    messagingSenderId: '706777644047',
    projectId: 'baladi-bd390',
    storageBucket: 'baladi-bd390.firebasestorage.app',
    iosBundleId: 'com.example.baladi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc8mLQlLt4CvA3Ncpb-BVczDgUxHB6UOg',
    appId: '1:706777644047:ios:98bcdf523df8d140adb77a',
    messagingSenderId: '706777644047',
    projectId: 'baladi-bd390',
    storageBucket: 'baladi-bd390.firebasestorage.app',
    iosBundleId: 'com.example.baladi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCW5AtQmCeOHHQFtR0_R-kS4BPAwOwkMU',
    appId: '1:706777644047:web:93ff890343177b88adb77a',
    messagingSenderId: '706777644047',
    projectId: 'baladi-bd390',
    authDomain: 'baladi-bd390.firebaseapp.com',
    storageBucket: 'baladi-bd390.firebasestorage.app',
    measurementId: 'G-THE7WZCVSG',
  );
}
